import { FaGithub, FaLinkedin, FaTelegram, FaEnvelope, FaWhatsapp } from "react-icons/fa";

export const THEME = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
];

export const Icons = {
  wa: <FaWhatsapp />,
  li: <FaLinkedin />,
  gh: <FaGithub />,
  tg: <FaTelegram />,
  email: <FaEnvelope />,
};
